version: '3.3'
services:
  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: root
    restart: always

  api:
    depends_on:
      - pgdb
    image: ecommerce-order:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgdb:5432/orders
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    restart: always